### ISSUE TITLE
Reproducibility with seeding

### ISSUE THREAD

**Issue by LeoLaugier** [LSIR/llm-mediator-simulation#11]
- [x] Seed Local Mistral and Local Server Mistral (sync) solved with #12 
- [x] Seed CharGPT (sync) solved with #12 
- [ ] Seed Mistral API (sync)
- [x] Seed async (ChatGPT, Local Mistral, Local Server Mistral, Mistral API)
- [ ] [Seed Gemini](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference#:~:text=gemini%2D1.5%2Dflash-,seed,-Optional%3A%20int), but [not yet available](https://github.com/google-gemini/generative-ai-python/issues/605) and [recent PR](https://github.com/google-gemini/generative-ai-python/pull/609/commits)
